### ISSUE TITLE
 execCommand在firefox下js复制会有失败

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/xe-clipboard#2]
火狐有权限限制，不绑定按钮操作的话，execCommand会返回false

**Comment by xuliangzhan** [comment]
execCommand  不应该直接调用的，必须用于事件内操作，不止 firefox 很多浏览器都会限制权限的
测试页面：https://xuliangzhan.github.io/xe-clipboard/

**Comment by wekerSnail** [comment]
我现在是使用了你这个库在vue-element-extends的右键菜单中，这个没法绑定事件操作，或者说用你提供的api实现的点击浏览器不认为是用户行为

**Comment by xuliangzhan** [comment]
应该可以吧，你用 firefox  打开试下 ，我试了都可以的，右键也是事件触发，应该所有支持 execCommand  的浏览器应该都可以的
https://xuliangzhan.github.io/xe-clipboard/
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api

**Comment by wekerSnail** [comment]
![image](https://user-images.githubusercontent.com/30314164/62342328-04273900-b519-11e9-87c8-e5de92e3aec2.png)
这样的情况，在firefox下会失败

**Comment by xuliangzhan** [comment]
你自行测试吧，copy 行为必须在事件之内，主流浏览器全都是可以支持的 https://xuliangzhan.github.io/xe-clipboard/

**Comment by wekerSnail** [comment]
我更新了你最新的版本确实可以了，问题我也找到了，之前的版本execCommand的第二个参数是直接传入的true，现在改成了默认传false不成功再传true的方式就可以了
![image](https://user-images.githubusercontent.com/30314164/62347886-d6002400-b52d-11e9-9609-10d76cf4518e.png)
