### ISSUE TITLE
复制失败

### ISSUE THREAD

**Issue by dengsha** [xuliangzhan/xe-clipboard#3]
**（必填）请填写问题描述或截图**
？拉取接口，copy接口返回的message，复制失败。发现，在promise里面使用Iphone会复制失败。
produceLink(param).then(resp => {
      setLoginLoading(false);
      if (resp.respStatus) {
        if (type === 'link') {
          const message = resp.respData.message || "";

          // setMessages(message);

          if (XEClipboard.copy(message)) {
            Toast.success("复制成功，请粘贴分享");
          } else {
            Toast.success("复制失败");
          }
        } else {
          Toast.success("邀约成功，正在下发短信");
        }
        return Router.back();
      }
      Toast.fail(resp.respData.message);
    });

**（必填）请填在线链接**
？

**请填写以下信息：**

- OS: ？
- Browser: ？只有ios系统有这个问题

**Comment by xuliangzhan** [comment]
copy 行为只允许在事件触发之内执行，其他的情况由浏览器决定是否有权限操作剪贴板，大部分浏览器是不允许事件之外操作剪贴板的
